name: CI
on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "README/*.png"
      - "README/*.svg"
      - "README/*.jpeg"
      - "README/*.jpg"
      - "README/*.md"
      - "LICENSE"
      - "readme/**/*"
env:
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: GO Build
        run: go build  -o harbor-telegram-bot -v
      - name: GO Test
        run: go test -v
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: harbor-telegram-bot_build-${{ github.run_number }}
          path: ./harbor-telegram-bot
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
          logout: true
      - name: Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/harbor-telegram-bot:build-${{ github.run_number }}