name: Docker Release
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "README/*.png"
      - "README/*.svg"
      - "README/*.jpeg"
      - "README/*.jpg"
      - "README/*.md"
      - "LICENSE"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "README/*.png"
      - "README/*.svg"
      - "README/*.jpeg"
      - "README/*.jpg"
      - "README/*.md"
      - "LICENSE"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/harbor-telegram-bot:build-${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/harbor-telegram-bot:1.1
            ${{ secrets.DOCKERHUB_USERNAME }}/harbor-telegram-bot:latest
