name: Go Lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone FoodManager-Backend repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_GO: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
